-- MySQL Script generated by MySQL Workbench
-- ven. 06 nov. 2020 01:14:28 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_MONTDOR
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_MONTDOR` ;

-- -----------------------------------------------------
-- Schema BD_MONTDOR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_MONTDOR` ;
USE `BD_MONTDOR` ;

-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tr_role_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tr_role_rol` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tr_role_rol` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol_role` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ux_rol_role` ON `BD_MONTDOR`.`tr_role_rol` (`rol_role`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`ts_user_usr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`ts_user_usr` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`ts_user_usr` (
  `usr_id` INT NOT NULL AUTO_INCREMENT,
  `usr_log` VARCHAR(12) NOT NULL,
  `usr_mail` VARCHAR(45) NOT NULL,
  `usr_pwd` CHAR(60) NOT NULL,
  `usr_avatar` BLOB NULL,
  `usr_isBanned` TINYINT NOT NULL DEFAULT 1,
  `usr_rol_id` INT NOT NULL,
  PRIMARY KEY (`usr_id`),
  CONSTRAINT `fk_usr_role_id`
    FOREIGN KEY (`usr_rol_id`)
    REFERENCES `BD_MONTDOR`.`tr_role_rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usr_role_id_idx` ON `BD_MONTDOR`.`ts_user_usr` (`usr_rol_id`);

CREATE UNIQUE INDEX `ux_usr_log` ON `BD_MONTDOR`.`ts_user_usr` (`usr_log`);

CREATE UNIQUE INDEX `ux_usr_mail` ON `BD_MONTDOR`.`ts_user_usr` (`usr_mail`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`t_favorite_fvr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`t_favorite_fvr` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`t_favorite_fvr` (
  `fvr_id` INT NOT NULL AUTO_INCREMENT,
  `fvr_ref` VARCHAR(45) NOT NULL,
  `fvr_usr_id` INT NOT NULL,
  PRIMARY KEY (`fvr_id`),
  CONSTRAINT `fk_fvr_usr_id`
    FOREIGN KEY (`fvr_usr_id`)
    REFERENCES `BD_MONTDOR`.`ts_user_usr` (`usr_rol_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fvr_usr_id_idx` ON `BD_MONTDOR`.`t_favorite_fvr` (`fvr_usr_id`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tr_category_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tr_category_cat` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tr_category_cat` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_ref` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ux_cat_ref` ON `BD_MONTDOR`.`tr_category_cat` (`cat_ref`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`t_recipe_rcp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`t_recipe_rcp` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`t_recipe_rcp` (
  `rcp_id` INT NOT NULL AUTO_INCREMENT,
  `rcp_creationDate` DATE NOT NULL,
  `rcp_modificationDate` DATE NULL,
  `rcp_title` VARCHAR(45) NOT NULL,
  `rcp_prepTime` INT NOT NULL,
  `rcp_cooktime` INT NOT NULL,
  `rcp_nbEater` INT NOT NULL,
  `rcp_message` TINYTEXT NULL,
  `rcp_photo` BLOB NULL,
  `rcp_usr_id` INT NOT NULL,
  `rcp_cat_id` INT NOT NULL,
  PRIMARY KEY (`rcp_id`),
  CONSTRAINT `fk_rcp_usr_id`
    FOREIGN KEY (`rcp_usr_id`)
    REFERENCES `BD_MONTDOR`.`ts_user_usr` (`usr_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rcp_cat_id`
    FOREIGN KEY (`rcp_cat_id`)
    REFERENCES `BD_MONTDOR`.`tr_category_cat` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rcp_usr_id_idx` ON `BD_MONTDOR`.`t_recipe_rcp` (`rcp_usr_id`);

CREATE INDEX `fk_rcp_cat_id_idx` ON `BD_MONTDOR`.`t_recipe_rcp` (`rcp_cat_id`);

CREATE UNIQUE INDEX `ux_rcp_titleUser` ON `BD_MONTDOR`.`t_recipe_rcp` (`rcp_usr_id`, `rcp_title`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`t_comment_cmt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`t_comment_cmt` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`t_comment_cmt` (
  `cmt_id` INT NOT NULL AUTO_INCREMENT,
  `cmt_message` TINYTEXT NOT NULL,
  `cmt_creationDate` DATE NOT NULL,
  `cmt_modificationDate` DATE NULL,
  `cmt_usr_id` INT NOT NULL,
  PRIMARY KEY (`cmt_id`),
  CONSTRAINT `fk_cmt_usr_id`
    FOREIGN KEY (`cmt_usr_id`)
    REFERENCES `BD_MONTDOR`.`ts_user_usr` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cmt_usr_id_idx` ON `BD_MONTDOR`.`t_comment_cmt` (`cmt_usr_id`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`t_ingredient_igr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`t_ingredient_igr` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`t_ingredient_igr` (
  `igr_id` INT NOT NULL AUTO_INCREMENT,
  `igr_label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`igr_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ux_igr_label` ON `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`t_step_stp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`t_step_stp` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`t_step_stp` (
  `stp_id` INT NOT NULL AUTO_INCREMENT,
  `stp_nb` INT NOT NULL,
  `stp_description` TINYTEXT NOT NULL,
  PRIMARY KEY (`stp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`t_rating_rtg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`t_rating_rtg` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`t_rating_rtg` (
  `rtg_id` INT NOT NULL AUTO_INCREMENT,
  `rtg_rate` INT NOT NULL,
  `rtg_usr_id` INT NOT NULL,
  `rtg_rcp_id` INT NOT NULL,
  PRIMARY KEY (`rtg_id`),
  CONSTRAINT `fk_rtg_user_id`
    FOREIGN KEY (`rtg_usr_id`)
    REFERENCES `BD_MONTDOR`.`ts_user_usr` (`usr_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rtg_rcp_id`
    FOREIGN KEY (`rtg_rcp_id`)
    REFERENCES `BD_MONTDOR`.`t_recipe_rcp` (`rcp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rtg_user_id_idx` ON `BD_MONTDOR`.`t_rating_rtg` (`rtg_usr_id`);

CREATE INDEX `fk_rtg_rcp_id_idx` ON `BD_MONTDOR`.`t_rating_rtg` (`rtg_rcp_id`);

CREATE UNIQUE INDEX `ux_rtg_usrRcp_ids` ON `BD_MONTDOR`.`t_rating_rtg` (`rtg_usr_id`, `rtg_rcp_id`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tr_unit_unt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tr_unit_unt` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tr_unit_unt` (
  `unt_id` INT NOT NULL AUTO_INCREMENT,
  `unt_label` VARCHAR(45) NULL,
  PRIMARY KEY (`unt_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ux_unt_label` ON `BD_MONTDOR`.`tr_unit_unt` (`unt_label`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tj_ingredientRecipe_irp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tj_ingredientRecipe_irp` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tj_ingredientRecipe_irp` (
  `irp_igr_id` INT NOT NULL,
  `irp_rcp_id` INT NOT NULL,
  `irp_amount` FLOAT NULL,
  `irp_unt_id` INT NOT NULL,
  CONSTRAINT `fk_irp_igr_id`
    FOREIGN KEY (`irp_igr_id`)
    REFERENCES `BD_MONTDOR`.`t_ingredient_igr` (`igr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_irp_rcp_id`
    FOREIGN KEY (`irp_rcp_id`)
    REFERENCES `BD_MONTDOR`.`t_recipe_rcp` (`rcp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_irp_unt_id`
    FOREIGN KEY (`irp_unt_id`)
    REFERENCES `BD_MONTDOR`.`tr_unit_unt` (`unt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_irp_rcp_id_idx` ON `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_rcp_id`);

CREATE INDEX `fk_irp_igr_id_idx` ON `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`);

CREATE INDEX `fk_irp_unt_id_idx` ON `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_unt_id`);

CREATE UNIQUE INDEX `ux_rcpIgr_id` ON `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_rcp_id`, `irp_igr_id`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tj_recipeFavorite_rfv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tj_recipeFavorite_rfv` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tj_recipeFavorite_rfv` (
  `rfv_rcp_id` INT NOT NULL,
  `rfv_fvr_id` INT NOT NULL,
  CONSTRAINT `fk_rfv_rcp_id`
    FOREIGN KEY (`rfv_rcp_id`)
    REFERENCES `BD_MONTDOR`.`t_recipe_rcp` (`rcp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rfv_fvr_id`
    FOREIGN KEY (`rfv_fvr_id`)
    REFERENCES `BD_MONTDOR`.`t_favorite_fvr` (`fvr_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rfv_fvr_id_idx` ON `BD_MONTDOR`.`tj_recipeFavorite_rfv` (`rfv_fvr_id`);

CREATE INDEX `fk_rfv_rcp_id_idx` ON `BD_MONTDOR`.`tj_recipeFavorite_rfv` (`rfv_rcp_id`);


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tj_commentRecipe_cmr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tj_commentRecipe_cmr` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tj_commentRecipe_cmr` (
  `cmr_cmt_id` INT NOT NULL,
  `cmr_rcp_id` INT NOT NULL,
  CONSTRAINT `fk_cmr_cmt_id`
    FOREIGN KEY (`cmr_cmt_id`)
    REFERENCES `BD_MONTDOR`.`t_comment_cmt` (`cmt_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmr_rcp_id`
    FOREIGN KEY (`cmr_rcp_id`)
    REFERENCES `BD_MONTDOR`.`t_recipe_rcp` (`rcp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cmr_rcp_id_idx` ON `BD_MONTDOR`.`tj_commentRecipe_cmr` (`cmr_rcp_id`) VISIBLE;

CREATE INDEX `fk_cmr_cmt_id_idx` ON `BD_MONTDOR`.`tj_commentRecipe_cmr` (`cmr_cmt_id`) VISIBLE;


-- -----------------------------------------------------
-- Table `BD_MONTDOR`.`tj_recipeStep_rst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_MONTDOR`.`tj_recipeStep_rst` ;

CREATE TABLE IF NOT EXISTS `BD_MONTDOR`.`tj_recipeStep_rst` (
  `rst_rcp_id` INT NOT NULL,
  `rst_stp_id` INT NOT NULL,
  CONSTRAINT `fk_rst_rcp_id`
    FOREIGN KEY (`rst_rcp_id`)
    REFERENCES `BD_MONTDOR`.`t_recipe_rcp` (`rcp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rst_stp_id`
    FOREIGN KEY (`rst_stp_id`)
    REFERENCES `BD_MONTDOR`.`t_step_stp` (`stp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rst_stp_id_idx` ON `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_stp_id`);

CREATE INDEX `fk_rst_rcp_id_idx` ON `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_rcp_id`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BD_MONTDOR`.`tr_role_rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_MONTDOR`;
INSERT INTO `BD_MONTDOR`.`tr_role_rol` (`rol_role`) VALUES ( 'admin');
INSERT INTO `BD_MONTDOR`.`tr_role_rol` (`rol_role`) VALUES ('user');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_MONTDOR`.`tr_category_cat`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_MONTDOR`;
INSERT INTO `BD_MONTDOR`.`tr_category_cat` (`cat_ref`) VALUES ('entrée');
INSERT INTO `BD_MONTDOR`.`tr_category_cat` (`cat_ref`) VALUES ('plat');
INSERT INTO `BD_MONTDOR`.`tr_category_cat` (`cat_ref`) VALUES ('dessert');
INSERT INTO `BD_MONTDOR`.`tr_category_cat` (`cat_ref`) VALUES ('boisson');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_MONTDOR`.`tr_unit_unt`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_MONTDOR`;
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('mL');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('cL');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('L');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('cc');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('cs');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('g');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('kg');
INSERT INTO `BD_MONTDOR`.`tr_unit_unt` (`unt_label`) VALUES ('pincée(s)');

COMMIT;


-- -----------------------------------------------------
-- PROCESS TO ADD A RECIPE
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_MONTDOR`;

-- -----------------------------------------------------
-- USER
-- -----------------------------------------------------
INSERT INTO `BD_MONTDOR`.`ts_user_usr` (`usr_log`, `usr_mail`,`usr_pwd`,`usr_isBanned`,`usr_rol_id`) 
VALUES ('main admin','mainadmin@hotmail.fr',12345,DEFAULT,1);

-- -----------------------------------------------------
-- INGREDIENTS
-- -----------------------------------------------------

INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('bavette(s)');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('sauce soja allégée en sel');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('sauce Worcestershire');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('poivre en grain');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('sauce bbq fumée');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('oignon en poudre');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('ail en poudre');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('sel');
INSERT INTO `BD_MONTDOR`.`t_ingredient_igr` (`igr_label`) 
VALUES ('piment de cayenne');

-- -----------------------------------------------------
-- RECIPE (stockage des durées en minutes)
-- -----------------------------------------------------

INSERT INTO `BD_MONTDOR`.`t_recipe_rcp` (`rcp_creationDate`, `rcp_title`,`rcp_prepTime`,`rcp_cooktime`,`rcp_nbEater`,`rcp_usr_id`,
`rcp_cat_id`) 
VALUES (now(),'Douceur de Smaug',10,240,6,1,2);

-- -----------------------------------------------------
-- JOIN TABLE INGREDIENT_RECIPE (stockage des durées en minutes integer à régler)
-- -----------------------------------------------------

INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (1,1,900,6);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (2,1,125,1);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (3,1,2,5);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (4,1,2,4);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (5,1,1,5);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (6,1,1,4);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (8,1,1,4);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (9,1,1,8);
INSERT INTO `BD_MONTDOR`.`tj_ingredientRecipe_irp` (`irp_igr_id`, `irp_rcp_id`,`irp_amount`,`irp_unt_id`) 
VALUES (7,1,0.5,4);

-- -----------------------------------------------------
-- STEPS
-- -----------------------------------------------------

INSERT INTO `BD_MONTDOR`.`t_step_stp` (`stp_nb`, `stp_description`) 
VALUES (1,'Couper des tranches de viande d’environ 3mm');
INSERT INTO `BD_MONTDOR`.`t_step_stp` (`stp_nb`, `stp_description`) 
VALUES (2,'Mélanger tous les ingrédients de la marinade dans un bol');
INSERT INTO `BD_MONTDOR`.`t_step_stp` (`stp_nb`, `stp_description`) 
VALUES (3,'Ajouter la marinade et la viande dans un sac hermétique');
INSERT INTO `BD_MONTDOR`.`t_step_stp` (`stp_nb`, `stp_description`) 
VALUES (4,'Faire mariner une bonne journée au frigo');
INSERT INTO `BD_MONTDOR`.`t_step_stp` (`stp_nb`, `stp_description`) 
VALUES (5,'Cuire au four à 80°C sur la grille du milieu ou la grille du bas pendant 4 heures, porte entrouverte, retourner à mi-cuisson');

-- -----------------------------------------------------
-- JOIN TABLE RECIPE_STEPS 
-- -----------------------------------------------------

INSERT INTO `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_rcp_id`, `rst_stp_id`) 
VALUES (1,1);
INSERT INTO `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_rcp_id`, `rst_stp_id`) 
VALUES (1,2);
INSERT INTO `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_rcp_id`, `rst_stp_id`) 
VALUES (1,3);
INSERT INTO `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_rcp_id`, `rst_stp_id`) 
VALUES (1,4);
INSERT INTO `BD_MONTDOR`.`tj_recipeStep_rst` (`rst_rcp_id`, `rst_stp_id`) 
VALUES (1,5);


COMMIT;

